# This is my first notebook. 
##Here I will learn to write some rudimentary python code and R code, in a notebook style setup, executing the same on a REMOTE Virtual Machine

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [6]:
# Read the CSV file iris.csv
import pandas as pd
df = pd.read_csv ("/content/gdrive/MyDrive/PGSS/Week1/iris.csv", header=None)
df.columns = ['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width', 'Class']
df

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Class         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [9]:
! pwd

/content

In [1]:
! top

=top - 19:32:30 up 4 min,  0 users,  load average: 0.75, 0.33, 0.14
Tasks:  11 total,   1 running,   9 sleeping,   0 stopped,   1 zombie
%Cpu(s):  8.4 us,  3.8 sy,  0.0 ni, 85.8 id,  1.9 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 13298580 total, 10333456 free,   850008 used,  2115116 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 12237676 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    108 root      20   0  676512 300132  32196 S 180.0  2.3   0:13.11 node
    125 root      20   0   63188   6824   5100 R   6.7  0.1   0:00.01 top
      1 root      20   0     992      4      0 S   0.0  0.0   0:00.47 docker-i+
      7 root      20   0  337768  47592  32256 S   0.0  0.4   0:00.53 node
     17 root      20   0   35892   4980   3884 S   0.0  0.0   0:00.50 tail
     27 root      20   0       0      0      0 Z   0.0  0.0   0:04.63 python3
     28 root      20   0  155880  41192  12808 S   0.0  0.3   0:00.40 colab-fi+
     53 root      20   0  198272  59296  14936 S   0.0  0.4   0:01.20 jupyter-+
     54 root      20   0  715340   5336   4260 S   0.0  0.0   0:00.00 dap_mult+
     71 root      20   0  464660  92064  23496 S   0.0  0.7   0:01.03 python3
     91 root      20   0  125904  14416   5364 S   0.0  0.1   0:00.01 python3
top - 19:32:33 up 4 min,  0 users,  load average: 0.75, 0.33, 0.14
Tasks:  11 total,   1 running,   9 sleeping,   0 stopped,   1 zombie
%Cpu(s): 18.2 us,  1.7 sy,  0.0 ni, 80.0 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 13298580 total, 10311916 free,   870636 used,  2116028 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 12220444 avail Mem


    108 root      20   0  692128 315948  32196 S  33.0  2.4   0:14.10 node
      7 root      20   0  339816  50540  32520 S   1.0  0.4   0:00.56 node
     71 root      20   0  464916  92244  23496 S   1.0  0.7   0:01.06 python3
     54 root      20   0  715340   6048   4572 S   0.7  0.0   0:00.02 dap_mult+
     91 root      20   0  127184  14600   5428 S   0.3  0.1   0:00.02 python3
      1 root      20   0     992      4      0 S   0.0  0.0   0:00.47 docker-i+
     17 root      20   0   35892   4980   3884 S   0.0  0.0   0:00.50 tail
     27 root      20   0       0      0      0 Z   0.0  0.0   0:04.63 python3
     28 root      20   0  155880  41192  12808 S   0.0  0.3   0:00.40 colab-fi+
     53 root      20   0  198272  59296  14936 S   0.0  0.4   0:01.20 jupyter-+
    125 root      20   0   63188   6824   5100 R   0.0  0.1   0:00.01 top
>

In [2]:
! nvidia-smi

Tue Jun 28 19:32:47 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

In [4]:
# Read the CSV file iris.csv
import pandas as pd
df2 = pd.read_csv ("https://raw.githubusercontent.com/nikolacao/CMU-PGSS-2022/main/Week01/iris.csv", header=None)
df2.columns = ['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width', 'Class']
df2

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]